/**
 * Bundled custom-underlying closes (equity Yahoo + commodity estimates).
 * Generated by `scripts/bake-custom-underlying-history.ts`.
 */
import historyJson from "@/lib/data/custom-underlying-history.json";
import type { CustomUnderlyingSpec } from "@/lib/underlying-benchmark";
import { resolveCustomUnderlyingSpec } from "@/lib/underlying-benchmark";
import type { ProductRecord } from "@/lib/types";
import { toLocalDateKey } from "@/lib/workbook/dates";

export type CustomUnderlyingHistoryEntry = {
  date: string;
  level: number;
  source: "yahoo" | "estimate";
};

export type CustomUnderlyingInstrumentHistory = {
  key: string;
  label: string;
  yahooSymbol?: string;
  estimate?: CustomUnderlyingSpec["estimate"];
  note?: string;
  entries: CustomUnderlyingHistoryEntry[];
};

type HistoryFile = {
  generatedAt: string;
  instruments: Record<string, CustomUnderlyingInstrumentHistory>;
};

const HISTORY = historyJson as HistoryFile;

/** Sorted ascending date → level maps per instrument key. */
const LOOKUP = new Map<string, { dates: string[]; levels: number[]; sources: string[] }>();

for (const [key, instrument] of Object.entries(HISTORY.instruments ?? {})) {
  const sorted = [...(instrument.entries ?? [])]
    .filter((e) => e.date && Number.isFinite(e.level) && e.level > 0)
    .sort((a, b) => a.date.localeCompare(b.date));
  LOOKUP.set(key, {
    dates: sorted.map((e) => e.date),
    levels: sorted.map((e) => e.level),
    sources: sorted.map((e) => e.source),
  });
}

function lookupOnOrBefore(
  key: string,
  date: Date,
): { level: number; date: string; source: string } | undefined {
  const row = LOOKUP.get(key);
  if (!row || row.dates.length === 0) return undefined;
  const target = toLocalDateKey(date);
  let lo = 0;
  let hi = row.dates.length - 1;
  let best = -1;
  while (lo <= hi) {
    const mid = (lo + hi) >> 1;
    if (row.dates[mid]! <= target) {
      best = mid;
      lo = mid + 1;
    } else {
      hi = mid - 1;
    }
  }
  if (best < 0) return undefined;
  return { level: row.levels[best]!, date: row.dates[best]!, source: row.sources[best]! };
}

/** Close (or estimate) for a known custom underlying on/before `date`. */
export function lookupCustomUnderlyingOnOrBefore(
  key: string,
  date: Date,
): number | undefined {
  return lookupOnOrBefore(key, date)?.level;
}

export function lookupCustomUnderlyingMetaOnOrBefore(
  key: string,
  date: Date,
): { level: number; date: string; source: string } | undefined {
  return lookupOnOrBefore(key, date);
}

/** Product-aware custom underlying level — undefined when unmapped or no history. */
export function resolveCustomUnderlyingLevel(
  product: ProductRecord | undefined,
  date: Date,
): number | undefined {
  const spec = resolveCustomUnderlyingSpec(product);
  if (!spec) return undefined;
  return lookupCustomUnderlyingOnOrBefore(spec.key, date);
}

export function getCustomUnderlyingHistoryStats(): {
  instruments: number;
  entries: number;
  generatedAt: string;
} {
  let entries = 0;
  for (const row of LOOKUP.values()) entries += row.dates.length;
  return {
    instruments: LOOKUP.size,
    entries,
    generatedAt: HISTORY.generatedAt ?? "",
  };
}
